/**
 * User identity types — anonymous GUID-based identity for deck publishing.
 *
 * Users generate a tentative UUID locally (crypto.randomUUID) and the
 * database service confirms/registers it on first publish.  No accounts,
 * no passwords — just a stable anonymous identifier.
 */

/** Minimal user record stored in the database. */
export interface UserIdentity {
  id: string;          // UUID v4
  createdAt: string;   // ISO 8601
  lastSeenAt: string;  // ISO 8601
}

/** Public profile summary (for browse / deck detail pages). */
export interface UserProfile {
  id: string;
  publishedCount: number;
  totalLikesReceived: number;
  createdAt: string;
}

/** Request body for user registration. */
export interface RegisterUserInput {
  tentativeId: string; // UUID generated by the frontend
}

/** Response from user registration. */
export interface RegisterUserResult {
  userId: string;
  isNew: boolean;
}
