// Icon Path Utilities — BA Hub Frontend Gen 2
// Based on original iconPaths.ts with modern TypeScript patterns

// Base asset path constants
export const IconPaths = {
  Flags: "/images/flags/",
  SpecIcons: "/images/icon specialisation/",
  SpecCovers: "/images/icon specialisation/illustrations/",
  Unit: "/images/labels/icons/",
  Weapon: "/images/weapons/",
  Ammunition: "/images/ammunition/",
  Portrait: "/images/unitportrait/",
  Modification: "/images/modifications/",
} as const;

// Dynamic path builder functions
export function toUnitIconPath(unitThumbnailPath: string): string {
  return encodeIconPath(IconPaths.Unit + unitThumbnailPath + ".png");
}

export function toCountryIconPath(countryThumbnailPath: string): string {
  return encodeIconPath(IconPaths.Flags + countryThumbnailPath + ".png");
}

export function toSpecializationIconPath(specializationThumbnailPath: string): string {
  return encodeIconPath(IconPaths.SpecIcons + specializationThumbnailPath + ".png");
}

export function toSpecializationCoverPath(specializationThumbnailPath: string): string {
  return encodeIconPath(IconPaths.SpecCovers + specializationThumbnailPath + ".png");
}

export function toWeaponIconPath(weaponId: string): string {
  return encodeIconPath(IconPaths.Weapon + weaponId + ".png");
}

/**
 * Converts an OptionPicture value (e.g. "Weapons\\M2_BROWNING" or "Modifications\\ARMOR1")
 * into a usable image path. The category prefix maps to the correct image directory.
 */
export function toOptionPicturePath(optionPicture: string): string {
  const parts = optionPicture.replace(/\\/g, '/').split('/');
  const category = parts.length > 1 ? parts[0] : '';
  const fileName = parts[parts.length - 1];
  if (category === 'Weapons') {
    return encodeIconPath(IconPaths.Weapon + fileName + ".png");
  }
  // Modifications and others → outline directory
  return encodeIconPath(IconPaths.Modification + "outline/" + fileName + ".png");
}

export function toAmmunitionIconPath(ammunitionId: string): string {
  return encodeIconPath(IconPaths.Ammunition + ammunitionId + ".png");
}

export function toPortraitIconPath(unitId: string): string {
  const split = unitId.split("\\");
  const prefix = split.slice(0, -1).join("/").toLowerCase();
  const fileName = split[split.length - 1].toUpperCase();
  return encodeIconPath(IconPaths.Portrait + prefix + "/" + fileName + "_BASIC.png");
}

/**
 * Safely encodes an icon path for URL usage, handling spaces and special characters
 */
export function encodeIconPath(path: string): string {
  const pathParts = path.split('/');
  const filename = pathParts[pathParts.length - 1];
  const directories = pathParts.slice(0, -1).join('/');
  const encodedFilename = filename.split(' ').join('%20');
  return directories ? `${directories}/${encodedFilename}` : encodedFilename;
}

// Static UI icon paths — complete map from game assets
export const UtilIconPaths = {
  AMMOTYPE_CLUSTER: "/images/ui/Cluster Ammo Icon.png",
  AMMOTYPE_FIRE: "/images/ui/Napalm Icon.png",
  AMMOTYPE_HEAT: "/images/ui/HEAT.png",
  AMMOTYPE_KE: "/images/ui/Kinetic.png",
  AntiCarIcon: "/images/ui/anti-car.png",
  ARMOR_HEAT: "/images/ui/HEAT Armor Icon.png",
  ARMOR_KE: "/images/ui/Kinetic Armor Icon.png",
  ATTACK_TYPE_BOMBING: "/images/ui/Tactic_bombing.png",
  ATTACK_TYPE_STRAFE: "/images/ui/Tactic_strafing.png",
  GroupIcon: "/images/ui/group.png",
  MOBILITY_FORWARD_HELI: "/images/ui/Forward speed.hel.png",
  MOBILITY_FORWARD_INFANTRY: "/images/ui/Forward speed.inf.png",
  MOBILITY_FORWARD_VEH: "/images/ui/Forward speed.car.png",
  MOBILITY_FORWARD_AIR: "/images/ui/Forward speed.air.png",
  MOBILITY_FUEL: "/images/ui/Fuel.png",
  MOBILITY_REVERSE_VEH: "/images/ui/Order_Reverse.png",
  STAT_ACCURACY: "/images/ui/Accuracy.png",
  STAT_AGILITY_AIR: "/images/ui/Agility turn rate.air.png",
  STAT_AGILITY_HELI: "/images/ui/Agility turn rate.hel.png",
  STAT_AIM: "/images/ui/Aim Icon.png",
  STAT_ARMOR: "/images/ui/Armor.png",
  STAT_CAPACITY: "/images/ui/Capacity Icon.png",
  STAT_COST: "/images/ui/local scenarios.png",
  STAT_FUEL: "/images/ui/Fuel_Stat.png",
  STAT_HEALTH_VEH: "/images/ui/Health points.car.png",
  STAT_HEALTH_INFANTRY: "/images/ui/Health points.inf.png",
  STAT_HEAVYLIFT: "/images/ui/heavy lift.png",
  STAT_OPTICS: "/images/ui/Optics.png",
  STAT_SEATS: "/images/ui/Seats.png",
  STAT_STEALTH: "/images/ui/Stealth.png",
  STAT_VISIBLE: "/images/ui/Visible Icon.png",
  STAT_WEIGHT: "/images/ui/Weight.png",
  TARGET_TYPE_AIRCRAFT: "/images/ui/Target Type Aircrafts Icon.png",
  TARGET_TYPE_HELI: "/images/ui/Target Type Helicopters Icon.png",
  TARGET_TYPE_INF: "/images/ui/Target Type Infantry Icon.png",
  TARGET_TYPE_MISSILE: "/images/ui/Target Type Missiles Icon.png",
  TARGET_TYPE_VEH: "/images/ui/Target Type Vehicles Icon.png",
  TARGET_TYPE_RDR: "/images/ui/Anti-radar Icon.png",
  TRAIT_AIRSUPERIORITY: "/images/ui/Air superiority.png",
  TRAIT_AIR_ALT_DOWN: "/images/ui/airalt_down.png",
  TRAIT_AIR_ALT_UP: "/images/ui/airalt_up.png",
  TRAIT_AIRDROP: "/images/ui/airdrop.png",
  TRAIT_AFTERBURNER: "/images/ui/afterburner.png",
  TRAIT_AMPHIBIOUS: "/images/ui/Amphibious.png",
  TRAIT_APS: "/images/ui/APS.png",
  TRAIT_CHANGE_ALT_AIR: "/images/ui/airalt_undefiend.png",
  TRAIT_COUNTERMEASURES_AIR: "/images/ui/Countermeasures.air.png",
  TRAIT_COUNTERMEASURES_HELI: "/images/ui/Countermeasures.hel.png",
  TRAIT_ECM: "/images/ui/ECM.png",
  TRAIT_LASERDESIGNATOR: "/images/ui/Laser designation.png",
  TRAIT_RADAR: "/images/ui/Radar.png",
  TRAIT_SMOKE: "/images/ui/Smoke.png",
  TRAIT_SMOKESCREEN: "/images/ui/Smoke screen.png",
  TRAIT_SPRINT: "/images/ui/Sprint.png",
  TRAIT_TOP_ATTACK: "/images/ui/Top Attack Type Icon.png",
  ABILITY_AFTERBURNER: "/images/ui/Ability_Afterburner.png",
  ABILITY_APS: "/images/ui/Ability_Aps.png",
  ABILITY_FLARES: "/images/ui/Ability_Flares.png",
  ABILITY_LASER_DESIGNATION: "/images/ui/Ability_LaserDesignation.png",
  ABILITY_RADAR: "/images/ui/Ability_Radar.png",
  ABILITY_RADAR_OFF: "/images/ui/Ability_RadarOff.png",
  ABILITY_SMOKE: "/images/ui/Ability_Smoke.png",
  ABILITY_SPRINT: "/images/ui/Ability_Sprint.png",
  ACTION_PANEL_HINTS: "/images/ui/ActionPanelHints_Icon.png",
  ADD_FRIEND: "/images/ui/Add Feiend.png",
  ADD_PLAYER: "/images/ui/Add Player Icon.png",
  AIRCRAFT: "/images/ui/aircraft.png",
  ALERT_ACTIVE: "/images/ui/Alert active.png",
  ALERT_OBJECTIVE: "/images/ui/AlertType_Objective.png",
  ALERT_OTHER: "/images/ui/AlertType_Other.png",
  ALERT_SPOTTED: "/images/ui/AlertType_Spotted.png",
  ALERT_SPOTTED_PLANE: "/images/ui/AlertType_SpottedPlane.png",
  ALERT_UNIT_LOST: "/images/ui/AlertType_UnitLost.png",
  ALERT_UNIT_UNDER_ATTACK: "/images/ui/AlertType_UnitUnderAttack.png",
  AMMO_TYPE: "/images/ui/ammo type.png",
  ANTI_DOWN_AIR: "/images/ui/anti-down.air.png",
  ANTI_UP_AIR: "/images/ui/anti-up.air.png",
  ATTACH: "/images/ui/Attach 2 Icon.png",
  BA_LOGO: "/images/ui/BA logo gradient icon.png",
  BACK_ARROW: "/images/ui/Back Arrow Icon.png",
  BACK_LEFT_VECTOR: "/images/ui/Back Left Vector.png",
  COPY: "/images/ui/Copy Icon.png",
  CURSOR_AIRDROP: "/images/ui/CursorAirdrop.png",
  CURSOR_ATTACK: "/images/ui/CursorAttack.png",
  CURSOR_DEFAULT: "/images/ui/CursorDefault.png",
  CURSOR_FAST_MOVE: "/images/ui/CursorFastMove.png",
  CURSOR_FAST_MOVE_AGGRESSIVE: "/images/ui/CursorFastMoveAggresive.png",
  CURSOR_FIRE_POS: "/images/ui/CursorFirePos.png",
  CURSOR_FIRE_SMOKE: "/images/ui/CursorFireSmoke.png",
  CURSOR_FOREST: "/images/ui/CursorForest.png",
  CURSOR_HIGH_SLOPES_ALT: "/images/ui/CursorHighSlopesAlt.png",
  CURSOR_IMPOSSIBLE: "/images/ui/CursorImpossible.png",
  CURSOR_LASER: "/images/ui/CursorLaser.png",
  CURSOR_LOAD: "/images/ui/CursorLoad.png",
  CURSOR_OUTSIDE_PLAY_ZONE: "/images/ui/CursorOutsidePlayZone.png",
  CURSOR_PAINTBRUSH: "/images/ui/CursorPaintbrush.png",
  CURSOR_PRECISION_STRIKE: "/images/ui/CursorPrecisionStrike.png",
  CURSOR_RESUPPLY: "/images/ui/CursorResupply.png",
  CURSOR_REVERSE: "/images/ui/CursorReverse.png",
  CURSOR_REVERSE_AGGRESSIVE: "/images/ui/CursorReverseAggresive.png",
  CURSOR_UNLOAD: "/images/ui/CursorUnload.png",
  DAMAGE: "/images/ui/damage.png",
  DECK_WIDE: "/images/ui/Deck Icon.png",
  DECK: "/images/ui/Deck Fill Icon.png",
  DECK_OUTLINE: "/images/ui/Deck Outline Icon.png",
  DELETE: "/images/ui/Delete Icon.png",
  DEPLOYMENT: "/images/ui/deployment.png",
  DISCORD_ICON: "/images/ui/Discord Icon.png",
  DOTS: "/images/ui/dots.png",
  DOTTED_LINE: "/images/ui/dotted line.png",
  DOWN_VECTOR: "/images/ui/Down Vector.png",
  EFFECTIVE_RANGE: "/images/ui/effective range.png",
  ESCAPE_MENU: "/images/ui/Escape menu.png",
  EVENT: "/images/ui/event 2.png",
  EXIT_GAME: "/images/ui/Exit Game Icon.png",
  EXPAND: "/images/ui/expand.png",
  FM_AMMO_EXPL: "/images/ui/FM_Ammo_Expl.png",
  FM_DURATION_LONG: "/images/ui/FM_Duration_Long.png",
  FM_DURATION_MEDIUM: "/images/ui/FM_Duration_Medium.png",
  FM_DURATION_SHORT: "/images/ui/FM_Duration_Short.png",
  FM_NO_AMMO_EXPL: "/images/ui/FM_NoAmmo_Expl.png",
  FM_NO_AMMO_PRECISE: "/images/ui/FM_NoAmmo_Precise.png",
  FM_NO_AMMO_SMOKE: "/images/ui/FM_NoAmmo_Smoke.png",
  FM_TARGETING_CREEP: "/images/ui/FM_Targeting_Creep.png",
  FM_TARGETING_LINE: "/images/ui/FM_Targeting_Line.png",
  FM_TARGETING_POINT: "/images/ui/FM_Targeting_Point.png",
  FORECON: "/images/ui/FORECON.png",
  GO_TO_LINK_SCENARIO_PART_1: "/images/ui/Go To Link Scenario Icon Part 1.png",
  GO_TO_LINK_SCENARIO_PART_2: "/images/ui/Go To Link Scenario Icon Part 2.png",
  HIDDEN: "/images/ui/hidden.png",
  HUD_AIRCRAFT_BACK_TO_BASE: "/images/ui/HUD Aircraft Back To Base Icon.png",
  HUD_AIRCRAFT_FUEL_BORDER: "/images/ui/HUD Aircraft Fuel Border.png",
  HUD_AIRCRAFT_FUEL_SCALE: "/images/ui/HUD Aircraft Fuel Scale.png",
  HUD_AIRCRAFT_HEALTH_BAR_BORDER: "/images/ui/HUD Aircraft Health Bar Border.png",
  HUD_AIRCRAFT_SCALE_INDICATOR: "/images/ui/HUD Aircraft Scale Indicator.png",
  HUD_AIRCRAFT_SCALE_LEFT_BAR: "/images/ui/HUD Aircraft Scale Left Bar.png",
  HUD_AIRCRAFT_SCALE_RIGHT_BAR: "/images/ui/HUD Aircraft Scale Right Bar.png",
  HUD_MAP_PING_MARKER_ATTACK: "/images/ui/HUD Map Ping Marker Attack Icon.png",
  HUD_MAP_PING_MARKER_ATTENTION: "/images/ui/HUD Map Ping Marker Attention Icon.png",
  HUD_MAP_PING_MARKER_DEFENSE: "/images/ui/HUD Map Ping Marker Defense Icon.png",
  HUD_MAP_PING_MARKER_SUPPLY: "/images/ui/HUD Map Ping Marker Supply Icon.png",
  HUD_PANIC_BACKGROUND: "/images/ui/HUD Panic Background.png",
  HUD_SELECTED_AMMO: "/images/ui/HUD Selected Ammo.png",
  HUD_SHOCK_BACKGROUND: "/images/ui/HUD Shock Background.png",
  ICON_PLAYER: "/images/ui/Icon_Player.png",
  ICON_TRANSPORT: "/images/ui/Icon_Transport.png",
  INFANTRY: "/images/ui/Infantry.png",
  INFINITY_AMMO: "/images/ui/infinity ammo.png",
  INPUT_BASE: "/images/ui/Input Base Icon.png",
  INVISIBLE: "/images/ui/Invisible Icon.png",
  INVITE: "/images/ui/INVITE.png",
  KICK: "/images/ui/Kick Icon.png",
  KILL_DEATH_RATIO: "/images/ui/kill_death_ratio.png",
  LABEL_ICON_PLANE_BOMB: "/images/ui/LabelIcon_Plane_Bomb.png",
  LABEL_ICON_PLANE_PARA: "/images/ui/LabelIcon_Plane_Para.png",
  LABEL_ICON_PLANE_PRECISE: "/images/ui/LabelIcon_Plane_Precise.png",
  LABEL_ICON_PLANE_RTB: "/images/ui/LabelIcon_Plane_RTB.png",
  LABEL_ICON_PLANE_STRAFE: "/images/ui/LabelIcon_Plane_Strafe.png",
  LEAST_FAVORITE_UNIT_SAMPLE: "/images/ui/Least Favorite Unit Sample Icon.png",
  LEAST_FAVORITE_SPEC: "/images/ui/Least  Favorite SPEC Icon.png",
  LIKE_ACTIVE: "/images/ui/Like active.png",
  LIKE_BASIC: "/images/ui/Like basic.png",
  LOAD_CAPACITY: "/images/ui/Load capacity.png",
  LOADER_CIRCLE: "/images/ui/Loader Circle.png",
  LOADING: "/images/ui/Loading Icon.png",
  LOCATION_MAP: "/images/ui/Location map.png",
  LOCK_OFF: "/images/ui/lock off.png",
  LOCK_ON: "/images/ui/lock on.png",
  LOCK: "/images/ui/Lock.png",
  LOCKED: "/images/ui/Locked Icon.png",
  MAIN_MENU_BUTTON_BORDER_BIG: "/images/ui/Main Menu Button Border Big.png",
  MAP_BORDER: "/images/ui/Map Border.png",
  MAP_PING_MARKER_ATTACK: "/images/ui/Map Ping Marker Attack Icon.png",
  MAP_PING_MARKER_ATTENTION: "/images/ui/Map Ping Marker Attention Icon.png",
  MAP_PING_MARKER_DEFENSE: "/images/ui/Map Ping Marker Defense Icon.png",
  MAP_PING_MARKER_LINE: "/images/ui/Map Ping Marker Line.png",
  MAP_PING_MARKER_POINT: "/images/ui/Map Ping Marker Point Icon.png",
  MAP_PING_MARKER_SUPPLY: "/images/ui/Map Ping Marker Supply Icon.png",
  MAP_PING_MARKER_TOP_RHOMB: "/images/ui/Map Ping Marker Top Rhomb Icon.png",
  MAP_DRAW_BUTTON_AA: "/images/ui/MapDrawButton_AA.png",
  MAP_DRAW_BUTTON_ARROW: "/images/ui/MapDrawButton_Arrow.png",
  MAP_DRAW_BUTTON_ARTY: "/images/ui/MapDrawButton_Arty.png",
  MAP_DRAW_BUTTON_ARTY_BLUR: "/images/ui/MapDrawButton_Arty_Blur.png",
  MAP_DRAW_BUTTON_ATTACK: "/images/ui/MapDrawButton_Attack.png",
  MAP_DRAW_BUTTON_ATTACK_BLUR: "/images/ui/MapDrawButton_Attack_Blur.png",
  MAP_DRAW_BUTTON_AVATAR: "/images/ui/MapDrawButton_Avatar.png",
  MAP_DRAW_BUTTON_AVATAR_BLUR: "/images/ui/MapDrawButton_Avatar_Blur.png",
  MAP_DRAW_BUTTON_DEF: "/images/ui/MapDrawButton_Def.png",
  MAP_DRAW_BUTTON_DEF_BLUR: "/images/ui/MapDrawButton_Def_Blur.png",
  MAP_DRAW_BUTTON_EXPL: "/images/ui/MapDrawButton_Exlp.png",
  MAP_DRAW_BUTTON_EXPL_BLUR: "/images/ui/MapDrawButton_Expl_Blur.png",
  MAP_DRAW_BUTTON_HELI: "/images/ui/MapDrawButton_Heli.png",
  MAP_DRAW_BUTTON_HELI_BLUR: "/images/ui/MapDrawButton_Heli_Blur.png",
  MAP_DRAW_BUTTON_INF: "/images/ui/MapDrawButton_Inf.png",
  MAP_DRAW_BUTTON_INF_BLUR: "/images/ui/MapDrawButton_Inf_Blur.png",
  MAP_DRAW_BUTTON_JET: "/images/ui/MapDrawButton_Jet.png",
  MAP_DRAW_BUTTON_JET_BLUR: "/images/ui/MapDrawButton_Jet_Blur.png",
  MAP_DRAW_BUTTON_PARA: "/images/ui/MapDrawButton_Para.png",
  MAP_DRAW_BUTTON_PARA_BLUR: "/images/ui/MapDrawButton_Para_Blur.png",
  MAP_DRAW_BUTTON_RECON: "/images/ui/MapDrawButton_Recon.png",
  MAP_DRAW_BUTTON_RECON_BLUR: "/images/ui/MapDrawButton_Recon_Blur.png",
  MAP_DRAW_BUTTON_TANK: "/images/ui/MapDrawButton_Tank.png",
  MAP_DRAW_BUTTON_TANK_BLUR: "/images/ui/MapDrawButton_Tank_Blur.png",
  MAP_DRAW_ARROW: "/images/ui/MapDraw_Arrow.png",
  MAP_DRAW_OUTLINE: "/images/ui/MapDraw_Outline.png",
  MAP_PREVIEW_OBJECTIVE_BODY_EMPTY: "/images/ui/MapPreview_ObjectiveBodyEmpty.png",
  MAP_PREVIEW_OBJECTIVE_BODY_FULL: "/images/ui/MapPreview_ObjectiveBodyFull.png",
  MAP_PREVIEW_OBJECTIVE_AMMO: "/images/ui/MapPreview_Objective_Ammo.png",
  MAP_PREVIEW_OBJECTIVE_ATTACK: "/images/ui/MapPreview_Objective_Attack.png",
  MAP_PREVIEW_OBJECTIVE_ATTENTION: "/images/ui/MapPreview_Objective_Attention.png",
  MAP_PREVIEW_OBJECTIVE_DEFEND: "/images/ui/MapPreview_Objective_Defend.png",
  MAP_PREVIEW_OBJECTIVE_FIRE: "/images/ui/MapPreview_Objective_Fire.png",
  MAP_PREVIEW_OBJECTIVE_PARA: "/images/ui/MapPreview_Objective_Para.png",
  MAP_PREVIEW_OBJECTIVE_RECON: "/images/ui/MapPreview_Objective_Recon.png",
  MAP_PREVIEW_OBJECTIVE_STAR: "/images/ui/MapPreview_Objective_Star.png",
  MAP_PREVIEW_SPAWNER_AIR: "/images/ui/MapPreview_SpawnerAir.png",
  MAP_PREVIEW_SPAWNER_BODY: "/images/ui/MapPreview_SpawnerBody.png",
  MAP_PREVIEW_SPAWNER_GROUND: "/images/ui/MapPreview_SpawnerGround.png",
  MAP_PREVIEW_SPAWNER_HELI: "/images/ui/MapPreview_SpawnerHeli.png",
  MAP_PREVIEW_SPAWNER_MIX: "/images/ui/MapPreview_SpawnerMix.png",
  MAP_PREVIEW_SPAWNER_SHIPS: "/images/ui/MapPreview_SpawnerShips.png",
  MATCH_PLAYED: "/images/ui/match_played.png",
  MEDAL_ADEPTUS_MECHANICUS: "/images/ui/Medal Adeptus mechanicus Icon.png",
  MEDAL_AIR_SUPERIORITY: "/images/ui/Medal Air Superiority Icon.png",
  MEDAL_AIRBORNE: "/images/ui/Medal Airborne Icon.png",
  MEDAL_ARMORED_FIST: "/images/ui/Medal Armored fist Icon.png",
  MEDAL_ARTILLERYMAN_AND_TARGETS: "/images/ui/Medal Artilleryman and Targets Icon.png",
  MEDAL_BERSERKER: "/images/ui/Medal Berserker Icon.png",
  MEDAL_DESTRUCTION: "/images/ui/Medal Destraction Icon.png",
  MEDAL_EXAMPLE: "/images/ui/medal example.png",
  MEDAL_FLAGS: "/images/ui/Medal Flags Icon.png",
  MEDAL_GUARDIAN_ANGEL: "/images/ui/Medal Guardian angel Icon.png",
  MEDAL_KD: "/images/ui/Medal KD Icon.png",
  MEDAL_KING_OF_THE_HILL: "/images/ui/Medal King of the Hill icon.png",
  MEDAL_LOGISTIC_OFFICER: "/images/ui/Medal Logistic officer Icon.png",
  MEDAL_LOSSES: "/images/ui/Medal Losses Icon.png",
  MEDAL_MEATGRINDER: "/images/ui/Medal Meatgrinder Icon.png",
  MEDAL_NO_ONE_LEFT_BEHIND: "/images/ui/Medal No One Left Behind Icon.png",
  MEDAL_NO_FLY_ZONE: "/images/ui/Medal No_Fly_Zone Icon.png",
  MEDAL_ONE_MAN_ARMY: "/images/ui/Medal One Man Army Icon.png",
  MEDAL_PURPLE_HEART: "/images/ui/Medal Purple heart Icon.png",
  MEDAL_PYRRHIC_VICTORY: "/images/ui/Medal Pyrrhic_victory Icon.png",
  MEDAL_RIDE_OF_THE_VALKYRIES: "/images/ui/Medal Ride of the Valkyries Icon.png",
  MEDAL_SPEED_DATING: "/images/ui/Medal Speed Dating Icon.png",
  MEDAL_THE_ART_OF_WAR: "/images/ui/Medal The art of war Icon.png",
  MEDAL_UNDERDOGS: "/images/ui/Medal Underdogs Icon.png",
  MEDAL_URBANIST: "/images/ui/Medal Urbanist Icon.png",
  MEM_PANEL_BG: "/images/ui/MemPanel_BG.png",
  MEM_PANEL_FRAME: "/images/ui/MemPanel_Frame.png",
  MESSAGE: "/images/ui/Message.png",
  MINI_DRONE: "/images/ui/Mini drone.png",
  MINIMAP_OBJ_PING_ATTACK: "/images/ui/MinimapObj_PingAttack.png",
  MINIMAP_OBJ_PING_ATTENTION: "/images/ui/MinimapObj_PingAttention.png",
  MINIMAP_OBJ_PING_HELP: "/images/ui/MinimapObj_PingHelp.png",
  MINIMAP_OBJ_PING_SUPPLY: "/images/ui/MinimapObj_PingSupply.png",
  MINIMAP_OBJ_SPAWN: "/images/ui/MinimapObj_Spawn.png",
  MINIMAP_OBJ_ZONE_CIRCLE: "/images/ui/MinimapObj_ZoneCircle.png",
  MINIMAP_OBJ_ZONE_RECT: "/images/ui/MinimapObj_ZoneRect.png",
  MINUS: "/images/ui/Minus Icon.png",
  MISSION_AVAILABLE: "/images/ui/mission_available.png",
  MISSION_COMPLETED_CINEMATIC: "/images/ui/mission_completed_cinematic.png",
  MISSION_COMPLETED_EASY: "/images/ui/mission_completed_easy.png",
  MISSION_COMPLETED_HARD: "/images/ui/mission_completed_hard.png",
  MISSION_COMPLETED_NONE: "/images/ui/mission_completed_none.png",
  MISSION_COMPLETED_NORMAL: "/images/ui/mission_completed_normal.png",
  MISSION_LOCKED: "/images/ui/mission_locked.png",
  MOBILITY: "/images/ui/Mobility Icon.png",
  MODIFICATION_ARMOR_SLOT: "/images/ui/Modification Armor Slot Icon.png",
  MODIFICATION: "/images/ui/Modification Icon.png",
  MUTE: "/images/ui/Mute.png",
  NEUTRAL_POINT: "/images/ui/Neutral point icon.png",
  NEW_TAG: "/images/ui/new tag.png",
  NEW_UNIT: "/images/ui/new unit.png",
  NEXT: "/images/ui/Next.png",
  NEXT_BUTTON: "/images/ui/next_button.png",
  NO_CONNECTION: "/images/ui/No connection.png",
  OBJECTIVE_ICON_AMMO: "/images/ui/ObjectiveIcon_IconAmmo.png",
  OBJECTIVE_ICON_ATTACK: "/images/ui/ObjectiveIcon_IconAttack.png",
  OBJECTIVE_ICON_ATTENTION: "/images/ui/ObjectiveIcon_IconAttention.png",
  OBJECTIVE_ICON_DESTROY: "/images/ui/ObjectiveIcon_IconDestroy.png",
  OBJECTIVE_ICON_HEAL: "/images/ui/ObjectiveIcon_IconHeal.png",
  OBJECTIVE_ICON_PARA: "/images/ui/ObjectiveIcon_IconPara.png",
  OBJECTIVE_ICON_RECON: "/images/ui/ObjectiveIcon_IconRecon.png",
  OBJECTIVE_ICON_STAR: "/images/ui/ObjectiveIcon_IconStar.png",
  OBJECTIVE_ICON_LETTER_A: "/images/ui/ObjectiveIcon_LetterA.png",
  OBJECTIVE_ICON_LETTER_B: "/images/ui/ObjectiveIcon_LetterB.png",
  OBJECTIVE_ICON_LETTER_C: "/images/ui/ObjectiveIcon_LetterC.png",
  OBJECTIVE_ICON_LETTER_D: "/images/ui/ObjectiveIcon_LetterD.png",
  OBJECTIVE_ICON_LETTER_E: "/images/ui/ObjectiveIcon_LetterE.png",
  OBJECTIVE_ICON_LETTER_F: "/images/ui/ObjectiveIcon_LetterF.png",
  OBJECTIVE_ICON_LETTER_G: "/images/ui/ObjectiveIcon_LetterG.png",
  OBJECTIVE_ICON_LETTER_H: "/images/ui/ObjectiveIcon_LetterH.png",
  OBJECTIVE_ICON_LETTER_I: "/images/ui/ObjectiveIcon_LetterI.png",
  OBJECTIVE_ICON_LETTER_J: "/images/ui/ObjectiveIcon_LetterJ.png",
  OBJECTIVE_ICON_LETTER_K: "/images/ui/ObjectiveIcon_LetterK.png",
  OBJECTIVE_ICON_LETTER_L: "/images/ui/ObjectiveIcon_LetterL.png",
  OBJECTIVE_ICON_LETTER_M: "/images/ui/ObjectiveIcon_LetterM.png",
  OBJECTIVE_ICON_LETTER_N: "/images/ui/ObjectiveIcon_LetterN.png",
  OBJECTIVE_ICON_LETTER_O: "/images/ui/ObjectiveIcon_LetterO.png",
  OBJECTIVE_ICON_LETTER_P: "/images/ui/ObjectiveIcon_LetterP.png",
  OBJECTIVE_ICON_LETTER_Q: "/images/ui/ObjectiveIcon_LetterQ.png",
  OBJECTIVE_ICON_LETTER_R: "/images/ui/ObjectiveIcon_LetterR.png",
  OBJECTIVE_ICON_LETTER_S: "/images/ui/ObjectiveIcon_LetterS.png",
  OBJECTIVE_ICON_LETTER_T: "/images/ui/ObjectiveIcon_LetterT.png",
  OBJECTIVE_ICON_LETTER_U: "/images/ui/ObjectiveIcon_LetterU.png",
  OBJECTIVE_ICON_LETTER_V: "/images/ui/ObjectiveIcon_LetterV.png",
  OBJECTIVE_ICON_LETTER_W: "/images/ui/ObjectiveIcon_LetterW.png",
  OBJECTIVE_ICON_LETTER_X: "/images/ui/ObjectiveIcon_LetterX.png",
  OBJECTIVE_ICON_LETTER_Y: "/images/ui/ObjectiveIcon_LetterY.png",
  OBJECTIVE_ICON_LETTER_Z: "/images/ui/ObjectiveIcon_LetterZ.png",
  ON_FOOT: "/images/ui/On Foot Icon.png",
  OPEN_MENU_BUTTON: "/images/ui/open menu button icon.png",
  OPEN_WHITE: "/images/ui/open white.png",
  OPEN_WORKSHOP_PAGE: "/images/ui/Open Workshop Page Icon.png",
  ORDER_AIRDROP: "/images/ui/Order_Airdrop.png",
  ORDER_ALTITUDE_HELI_DOWN: "/images/ui/Order_AltitudeHeli_Down.png",
  ORDER_ALTITUDE_HELI_UP: "/images/ui/Order_AltitudeHeli_Up.png",
  ORDER_ALTITUDE_PLANE_DOWN: "/images/ui/Order_AltitudePlane_Down.png",
  ORDER_ALTITUDE_PLANE_UP: "/images/ui/Order_AltitudePlane_Up.png",
  ORDER_ATTACK: "/images/ui/Order_Attack.png",
  ORDER_BACK_TO_BASE: "/images/ui/Order_BackToBase.png",
  ORDER_BOMBING_RUN: "/images/ui/Order_BombingRun.png",
  ORDER_CANCEL: "/images/ui/Order_Cancel.png",
  ORDER_FAST_MOVE: "/images/ui/Order_FastMove.png",
  ORDER_FIRE_MISSION: "/images/ui/Order_FireMission.png",
  ORDER_FORCE_FIRE: "/images/ui/Order_ForceFire.png",
  ORDER_HOLD_FIRE: "/images/ui/Order_HoldFire.png",
  ORDER_HOLD_FIRE_ON: "/images/ui/Order_HoldFireOn.png",
  ORDER_PRECISION_STRIKE: "/images/ui/Order_PrecisionStrike.png",
  ORDER_REVERSE_VEH_ALT: "/images/ui/Order_Reverse_Alt.png",
  ORDER_STOP: "/images/ui/Order_Stop.png",
  ORDER_STRAFING_RUN: "/images/ui/Order_StrafingRun.png",
  ORDER_UNLOAD: "/images/ui/Order_Unload.png",
  PENETRATION: "/images/ui/penetration.png",
  PHOTOCARD_MODE_IN: "/images/ui/photocard_mode_in.png",
  PHOTOCARD_MODE_OUT: "/images/ui/photocard_mode_out.png",
  PIN: "/images/ui/pin.png",
  PINNED: "/images/ui/pinned.png",
  PLAY: "/images/ui/play.png",
  PLAYABLE_ZONE: "/images/ui/playable zone.png",
  PLAYERS: "/images/ui/Players.png",
  PLAYTIME: "/images/ui/playtime.png",
  PLUS: "/images/ui/plus.png",
  POINTS: "/images/ui/Points Icon.png",
  PRIVATE: "/images/ui/Private Icon.png",
  PROFILE: "/images/ui/profile icon.png",
  QUESTION_MARK: "/images/ui/question mark.png",
  RANGE: "/images/ui/range.png",
  READY: "/images/ui/ready.png",
  REFRESH: "/images/ui/Refresh Icon.png",
  RELOAD: "/images/ui/reload.png",
  RESTART: "/images/ui/Restart.png",
  REWIND: "/images/ui/Rewind Icon.png",
  RU_FLAG: "/images/ui/RU_FLAG.png",
  SCENARIO_BA: "/images/ui/Scenario BA Icon.png",
  SCENARIO_LOCAL: "/images/ui/Scenario Local Icon.png",
  SCENARIO_LOCAL_LINKED: "/images/ui/Scenario Local Linked Icon.png",
  SCENARIO_REMOTE: "/images/ui/Scenario Remote Icon.png",
  SCENARIO_REMOTE_LINKED: "/images/ui/Scenario Remote Linked Icon.png",
  SELECTED_ICON: "/images/ui/selected_icon.png",
  SEND_MESSAGE: "/images/ui/send message.png",
  SETTINGS: "/images/ui/Settings Icon.png",
  SHARE: "/images/ui/Share Icon.png",
  SHOP: "/images/ui/shop.png",
  SKIN_PAINT: "/images/ui/Skin (Paint) Icon.png",
  SKULL_GRAY: "/images/ui/Skull gray.png",
  SKULL: "/images/ui/Skull.png",
  SPAWN_LABEL_ICON_AIR: "/images/ui/SpawnLabel_IconAir.png",
  SPAWN_LABEL_ICON_DEFAULT: "/images/ui/SpawnLabel_IconDefault.png",
  SPAWN_LABEL_ICON_GROUND: "/images/ui/SpawnLabel_IconGround.png",
  SPAWN_LABEL_ICON_HELICOPTER: "/images/ui/SpawnLabel_IconHelicopter.png",
  SPAWN_LABEL_ICON_SHIP: "/images/ui/SpawnLabel_IconShip.png",
  SPECTATOR: "/images/ui/Spectator Icon.png",
  SPEC_RU_VDV: "/images/ui/SPEC_RU_VDV_0.png",
  SPEC_US_AIRMOBILE: "/images/ui/SPEC_US_Airmobile.png",
  SPEC_US_MARINES: "/images/ui/SPEC_US_Marines.png",
  SPEED_BACKWARDS_CAR: "/images/ui/Speed backwards.car.png",
  SPHERE_OBJECTIVE_ZONE: "/images/ui/sphere objective zone.png",
  SPHERE_TRIGGER: "/images/ui/sphere trigger.png",
  SQUARE_OUTLINE: "/images/ui/Square Outline Icon.png",
  STAR_MESSAGE: "/images/ui/Star message icon.png",
  STAR: "/images/ui/star.png",
  STATS_DIFF_DOWN: "/images/ui/Stats Diff Down Icon.png",
  STATS_DIFF_UP: "/images/ui/Stats Diff Up Icon.png",
  STAY_HIDDEN: "/images/ui/Stay hidden.png",
  STEAM_ICON_HOVER: "/images/ui/Steam Icon Hover.png",
  STEAM_ICON: "/images/ui/Steam Icon.png",
  SUPPLY_BUTTON_ALLIES_GIVE: "/images/ui/SupplyButton_AlliesGive.png",
  SUPPLY_BUTTON_ALLIES_SHARE: "/images/ui/SupplyButton_AlliesShare.png",
  SUPPLY_BUTTON_AMMO: "/images/ui/SupplyButton_Ammo.png",
  SUPPLY_BUTTON_HEALING: "/images/ui/SupplyButton_Healing.png",
  SUPPLY_BUTTON_REPAIR: "/images/ui/SupplyButton_Repair.png",
  SUPPLY_BUTTON_TURNED_OFF: "/images/ui/SupplyButton_TurnedOff.png",
  SUPPLY_PANEL_PORTRAIT: "/images/ui/SupplyPanel_Portrait.png",
  SWITCH_REFRESH: "/images/ui/Switch Refresh Icon.png",
  TARGETING: "/images/ui/Targeting Icon.png",
  TASK_MARKER_AIRDROP: "/images/ui/TaskMarker_Airdrop.png",
  TASK_MARKER_AMMO: "/images/ui/TaskMarker_Ammo.png",
  TASK_MARKER_ATTACK: "/images/ui/TaskMarker_Attack.png",
  TASK_MARKER_ATTENTION: "/images/ui/TaskMarker_Attention.png",
  TASK_MARKER_DESTROY: "/images/ui/TaskMarker_Destroy.png",
  TASK_TASK_MARKER_HELP: "/images/ui/TaskMarker_Help.png",
  TASK_MARKER_RECON: "/images/ui/TaskMarker_Recon.png",
  TASK_MARKER_TASK: "/images/ui/TaskMarker_Task.png",
  TIME: "/images/ui/Time Icon.png",
  TOGGLE_OFF: "/images/ui/Toggle Off Icon.png",
  TOGGLE_ON: "/images/ui/Toggle On Icon.png",
  TOGGLE_ON_WHITE: "/images/ui/toggle on.png",
  TOGGLE_CHECKMARK: "/images/ui/toggle_checkmark.png",
  UNBAN_CLICK: "/images/ui/Unban click.png",
  UNBAN_HOVER: "/images/ui/Unban hover.png",
  UNMUTE: "/images/ui/Unmute.png",
  UP_VECTOR: "/images/ui/Up Vector.png",
  UPLOAD: "/images/ui/Upload Icon.png",
  USA_FLAG: "/images/ui/usa flag.png",
  US_PILOT: "/images/ui/US_PILOT.png",
  VDV_AGS: "/images/ui/VDV_AGS.png",
  VIGNETTE_RULE_ALT: "/images/ui/Vignette_RuleAlt.png",
  VIGNETTE_RULE_SPEED: "/images/ui/Vignette_RuleSpeed.png",
  WARNING: "/images/ui/Warning Icon.png",
  WARNING_ORANGE: "/images/ui/WarningOrange.png",
  WARNING_RED: "/images/ui/WarningRed.png",
  WHITE_LOGO: "/images/ui/white logo.png",
  WIN_RATE: "/images/ui/win_rate.png",
  WIP_BRIEFING: "/images/ui/WIP_Briefing.png",
  WIP_INTELLIGENCE: "/images/ui/WIP_Intelligence.png",
  YOUTUBE_ICON_HOVER: "/images/ui/Youtube Icon Hover.png",
  YOUTUBE_ICON: "/images/ui/Youtube Icon.png",

  PLACEHOLDER: "/images/ui/bug.png",
} as const;

// Type helper for icon path keys
export type UtilIconKey = keyof typeof UtilIconPaths;
