name: Type Check

on:
  pull_request:
    branches: [main, dev]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/package.json'
      - '**/tsconfig.json'

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build -w shared
      - run: npm run type-check
